apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd
  namespace: uniris-metrics
  labels:
    app: statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd
  template:
    metadata:
      labels:
        component: graphite
        app: statsd
    spec:
      serviceAccountName:
      containers:
        - name: statsd
          image: statsd/statsd:v0.9.0
          ports:
            - name: udp-statsd
              containerPort: 8125
              protocol: UDP
          resources:
            requests:
              cpu: 600m
              memory: 256Mi

---
